name: roar_animal_dino_sounds
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.2+3

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  audioplayers: ^0.14.0
  firebase_admob: ^0.9.3+1
  flame: ^0.18.2
  shared_preferences: ^0.5.6+3


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
     - assets/
     - assets/images/enemy/toothless.png
     - assets/images/target/pandaSleep.png
     - assets/images/target/pandaUp.png
     - assets/images/ui/background.png
     - assets/puzzles/p01.jpg
     - assets/puzzles/p02.jpg
     - assets/puzzles/p03.jpg
     - assets/puzzles/p03.jpg
     - assets/puzzles/p03.jpg
     - assets/puzzles/p04.jpg
     - assets/puzzles/p05.jpg
     - assets/puzzles/p06.jpg
     - assets/puzzles/p07.jpg
     - assets/puzzles_image/p0.png
     - assets/puzzles_image/p1.png
     - assets/puzzles_image/p2.png
     - assets/puzzles_image/p3.png
     - assets/puzzles_image/p4.png
     - assets/puzzles_image/p5.png
     - assets/puzzles_image/p6.png
     - assets/puzzles_image/p7.png
     - assets/puzzles_image/p8.png
     - assets/puzzles_image/p9.png
     - assets/puzzles_image/p10.png
     - assets/puzzles_image/p11.png
     - assets/puzzles_image/p12.png
     - assets/images/ui/sound_enabled.png
     - assets/images/ui/sound_disabled.png
     - assets/audio/background.mp3
     - assets/audio/home.mp3
     - assets/audio/break.mp3
     - assets/audio/lifeloss.mp3

  #  fonts:




  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
